
GET https://localhost:7119/api/cities/
Accept: application/xml

###

GET https://localhost:7119/api/cities/9/pointsofinterest
Accept: application/json

###

POST https://localhost:7119/api/cities/3/pointsofinterest
Content-Type: application/json 
{
"name": "Dupa ziduri", 
"description": "In spate la Livada Postei frumos"
}

###

PUT https://localhost:7119/api/cities/1/pointsofinterest/1
Content-Type: application/json 
{
"name": "Updated - Piata Sfatului", 
"description": "Updated - cel mai vizitat"
}

###

PATCH https://localhost:7119/api/cities/1/pointsofinterest/1
Content-Type: application/json 
[
  {
    "op": "replace", 
    "path": "/name", 
    "value": "Updated Piata Sfatului"
  }
]

###

PATCH https://localhost:7119/api/cities/1/pointsofinterest/1
Content-Type: application/json 
[
  {
    "op": "remove", 
    "path": "/name"
  }
]

###
DELETE https://localhost:7119/api/cities/1/pointsofinterest/2
Accept: application/json