
GET https://localhost:7119/api/cities/
Accept: application/xml

###

GET https://localhost:7119/api/cities/9
Accept: application/json

###

POST https://localhost:7119/api/cities/1/pointsofinterest
Content-Type: application/json 
{
  "name": "Dupa ziduri", 
  "description": "In spate la Livada Postei frumos"
}