name: Trigger auto deployment for my-first-container-app23

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-first-container-app23-AutoDeployTrigger-1de0264e-5c33-4f2d-a11e-c5a40398a670.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYFIRSTCONTAINERAPP23_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYFIRSTCONTAINERAPP23_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYFIRSTCONTAINERAPP23_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.MYFIRSTCONTAINERAPP23_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYFIRSTCONTAINERAPP23_REGISTRY_PASSWORD }}
          containerAppName: my-first-container-app23
          resourceGroup: AzureResourceGroupOne
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


